/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzastorect467;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author trant
 */
public class JFrameThemSP extends javax.swing.JFrame {

    /**
     * Creates new form JFrameThemSP
     */
    public JFrameThemSP() {
        initComponents();
        setTitle("Quản lý của hàng bánh Pizza");
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(java.awt.Color.ORANGE); //Set màu cho background giao diện
        
        btnthemSP.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                themSP();
            }
        });
        
        
        btnback.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                         new JFrameSanPham().setVisible(true);
                    }
                });
            }
        });
    }
    
    public void themSP(){
        String tenSP = txttenSP.getText();
        String giaSP = txtgiaSP.getText();
        if(tenSP.equals("") || giaSP.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ thông tin sản phẩm cần thêm");
        }else if(Integer.parseInt(giaSP) <= 10000){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập giá tiền SP lớn hơn 10,000 đ");
        }
        else{
            JDBC_Connect connection = new JDBC_Connect();
            Connection conn = connection.connect();
            String query_add_SP = "insert into sanpham(TenSP, GiaSP) values(?, ?)";
            
            PreparedStatement pstm = null;
            try {
                pstm = conn.prepareStatement(query_add_SP);
                
                pstm.setString(1, tenSP);
                pstm.setString(2, giaSP);
                
                
                int row = pstm.executeUpdate();
                if(row != 0){
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                    setVisible(false);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                         new JFrameSanPham().setVisible(true);
                    }
                });
                }
                
                //Thực hiện đóng kết nối
                conn.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttenSP = new javax.swing.JTextField();
        txtgiaSP = new javax.swing.JTextField();
        btnthemSP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setText("Trở Về");
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset_img/14661311.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 240, 540));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset_img/Pizza-icon.png"))); // NOI18N
        jLabel2.setText("Thêm Sản Phẩm");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 0, 570, 120));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên Sản Phẩm:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Giá:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));
        getContentPane().add(txttenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 240, 40));
        getContentPane().add(txtgiaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 240, 40));

        btnthemSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnthemSP.setText("Thêm Sản Phẩm");
        getContentPane().add(btnthemSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameThemSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameThemSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameThemSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameThemSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameThemSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnthemSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtgiaSP;
    private javax.swing.JTextField txttenSP;
    // End of variables declaration//GEN-END:variables
}
